services:
  backend:
    container_name: kinoafisha_server
    image: kinoafisha_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    container_name: kinoafisha_client
    image: kinoafisha_client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"


